def draw(mistakes):
    if mistakes == 0:
        print("      ")
        print("     ")
        print("     ")
        print("       ")
        print("       ")
        print(" ")
    if mistakes == 1:
        print("      ")
        print("|    ")
        print("|    ")
        print("|      ")
        print("|      ")
        print("|")
    if mistakes == 2:
        print("______")
        print("|    ")
        print("|    ")
        print("|      ")
        print("|      ")
        print("|")
    if mistakes == 3:
        print("______")
        print("|    ")
        print("|   O")
        print("|      ")
        print("|      ")
        print("|")
    if mistakes == 4:
        print("______")
        print("|    ")
        print("|   O")
        print("|   |  ")
        print("|      ")
        print("|")
    if mistakes == 5:
        print("______")
        print("|    ")
        print("|   O")
        print("|  /|  ")
        print("|      ")
        print("|")
    if mistakes == 6:
        print("______")
        print("|    ")
        print("|   O")
        print("|  /|\\")
        print("|      ")
        print("|")
    if mistakes == 7:
        print("______")
        print("|    ")
        print("|   O")
        print("|  /|\\")
        print("|  /   ")
        print("|")
    if mistakes == 8:
        print("______")
        print("|    ")
        print("|   O")
        print("|  /|\\")
        print("|  / \\")
        print("|")
    if mistakes == 9:
        print("______")
        print("|   |")
        print("|   O")
        print("|  /|\\")
        print("|  / \\")
        print("|")
